name: React CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: CI=false npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

      - name: Check Build Directory
        run: |
              if [ ! -d "/home/runner/work/ch-frontend/ch-frontend/build" ]; then
              echo "Build directory not found!"
              exit 1
              fi

      - name: Upload with lftp
        run: |
              sudo apt-get update && sudo apt-get install -y lftp
              lftp -e "mirror -R /home/runner/work/ch-frontend/ch-frontend/build /destination/path; bye" || {
              echo "lftp upload failed!"
              exit 1
              }

      - name: Set up environment
        run: |
          sudo apt-get update && sudo apt-get install -y lftp

      - name: Verify Installation
        run: lftp --version

      - name: Check User Permissions
        run: id



  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Deploy to Hostinger
        env:
          HOSTINGER_FTP_SERVER: ${{ secrets.HOSTINGER_FTP_SERVER }}
          HOSTINGER_FTP_USERNAME: ${{ secrets.HOSTINGER_FTP_USERNAME }}
          HOSTINGER_FTP_PASSWORD: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -u $HOSTINGER_FTP_USERNAME,$HOSTINGER_FTP_PASSWORD $HOSTINGER_FTP_SERVER <<EOF
          mirror -R build /path/to/hostinger/directory
          bye
          EOF
